### PR TITLE
Added GitHub Actions for testing

### PR DESCRIPTION
**Pull request by ThatXliner**

### CODE REVIEW

**Comment by adamsol** [comment]
Nice, thank you!

---

Since there is testing against different Python versions, could you also add testing against GCC in addition to Clang?

```
python test.py -c=gcc
````

Sometimes the two compilers behave differently, so it would be handy to have them both tested automatically.

---

I can see the action properly run in your fork (https://github.com/ThatXliner/Pyxell/actions/runs/539085397), but the job name is "build". Shouldn't it be "test"?

---

Also, I'm wondering how the failed tests would be displayed. It's probably necessary to add some non-zero exit code in `test.py`.

**Comment by ThatXliner** [comment]
Maybe I should name the entire file name to CI and that specific job "test"

**Comment by ThatXliner** [comment]
So I updated it here: https://github.com/ThatXliner/Pyxell/actions/runs/541236964

> Also, I'm wondering how the failed tests would be displayed. It's probably necessary to add some non-zero exit code in `test.py`.

yes, definitely

**Comment by adamsol** [comment]
Could you also add that change in `test.py`? It should be as simple as:

```
if failed:
    sys.exit(1)
```

And it would be great to see that the Github action turns red when a test fails. So maybe change some test output and commit it to a temporary branch. When it works, the PR will be ready to merge :-)

**Comment by ThatXliner** [comment]
Got it

**Comment by adamsol** [comment]
Thanks!

Now I don't know why [this](https://github.com/ThatXliner/Pyxell/runs/1841656588) has failed, I'll need to investigate. It's probably something wrong with the test script, since the failed tests are not displayed in the output.

**Comment by adamsol** [comment]
I hope to have fixed that in 1f9e1f572822f21b46d895299bde490a1eab32c0.

**Pull request merged**
